# Generated by Django 3.2.9 on 2021-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
