# Generated by Django 3.2.9 on 2021-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movietitle',
            field=models.TextField(null=True),
        ),
    ]
