# Generated by Django 3.2.9 on 2021-11-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_review_movietitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
