# Generated by Django 3.2.9 on 2021-11-21 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0014_review_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
